app:
  sync_interval: 5m
  username_replacements:
    - from: "@acme.com"
      to: ""
    - from: "@"
      to: ":"
  groupname_replacements:
    - from: "|all"
      to: ""
  remove_limit: 10
  ban_before_remove_duration: 168h # 7d

ldap:
  address: "localhost:10210"
  bind_dn: "cn=admin,dc=example,dc=org"
  bind_password_env_var: "LDAP_PASSWORD"
  base_dn: "dc=example,dc=org"
  users:
    filter: "(&(objectClass=posixAccount)(ou=People))"
    username_attribute_type: "cn"
    uid_attribute_type: "uid"
    first_name_attribute_type: "givenName"
  groups:
    filter: "(objectClass=posixGroup)"
    groupname_attribute_type: "cn"
    member_uid_attribute_type: "memberUid"

ytsaurus:
  proxy: localhost:10110
  apply_user_changes: true
  apply_group_changes: true
  apply_member_changes: true
  timeout: 1s
  log_level: DEBUG

logging:
  level: WARN
  is_production: true