apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ytsaurus-identity-sync.fullname" . }}
  labels:
    {{- include "ytsaurus-identity-sync.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- tpl (required "syncConfig is not provided" .Values.syncConfig) . | nindent 4 }}
